### ISSUE TITLE
Not Symfony 4 compatible at all

### ISSUE THREAD

**Issue by NMe84** [jjalvarezl/JjalvarezlPDFjsViewerBundle#8]
I'm sad to say there are many things wrong here. For one thing, you say you are Symfony 4 compatible when you aren't by default. Symfony 4 doesn't use the `web` folder anymore (the default is now `public`), yet you have `web` hard coded in your ViewerController.

Secondly the bundle makes heavy use of getting services by name through the container, which has been deprecated for a long time. You should be using dependency injection.

Lastly, you are using `cp` on the command line rather than simply using [https://www.php.net/manual/en/function.copy.php](copy), which is platform independent. Not to mention the problem with spaces that you solved in the master build but never published into a release.

I appreciate the work you've put into this but as is this bundle is nearly unusable. It only works out of the box if you're using Symfony 3 and with these three issues I already found there is actually more work required to get your bundle to work than it would be to manually replicate its functionality. You should probably update your readme and Packagist entry to reflect this because I just wasted an hour on something that could never have worked without extensive refactoring.

**Comment by jjalvarezl** [comment]
Of course, that is evident. As you can see obviously you did not read the README of this bundle, Symfony 4 is NOT compatible at all, that's why I obviously made a unstable tag on Symphony 4, and I mentioned in this bundle. If you know too much, update this bundle is pretty simple. Just provide a solution, make a fork and request a pull. I can not provide all for free, I need some collaboration or money contribution to maintain this bundle updated with the last Symfony 4 changes.

**Comment by NMe84** [comment]
No need to be an asshole about it. The first line of your README is this:

> This bundle provides a simple integration of the "PDF.JS library" from mozilla into Symfony 4 with different custom parameters.

The entire readme doesn't make a single other reference to Symfony versions. And sure, the sf3 branch has the same sentence but why would I even look at that if your packagist entry says this?

> This bundle provides an integration of pdf.js from mozilla with Symfony 4 framework and customizable parameters on server side.

Nothing tells anyone about having to lock to certain versions and the only version on Packagist that is actually Symfony 4 compatible is not even tagged for release yet.

But hey, if this is how you want to deal with comments and suggestions, go ahead. It doesn't speak for your professionalism.
